### ISSUE TITLE
prepWidget() Error on fresh install after entering FordPass login data. 

### ISSUE THREAD

**Issue by Igmiller** [tonesto7/fordpass-scriptable#100]
Just upgrading to latest version and did a clean install.  Entered VIN, U/N, PWD and get an Errors Logged message. 

prepWidget() Error: TypeError:
undefined is not an object (evaluating
"vehicleData.capabilities.includes')

After this, whenever I tap the script, I get a quick loading icon for 1 second then nothing happens.   Setting up a widget to it just shows the default widget logo. 

I'm in Canada if that makes a difference but I have been using the original script since December without issue.

**Comment by landoncastle** [comment]
Getting the same error.

**Comment by Igmiller** [comment]
The latest update that’s available as of May 12th, 2022 has resolved this issue.
