### ISSUE TITLE
"Advanced Controls" Issue

### ISSUE THREAD

**Issue by tkljr** [tonesto7/fordpass-scriptable#11]
v1.1.0

"Trail Light Check Control" brings up "SecuriAlert" functions
"Abort"  brings up "Trailer Light Check" functions

Possible issue: "Abort" quits script, if it should go back to the main screen then it's an issue

**Comment by tonesto7** [comment]
You must be using an older version of the script

**Comment by tkljr** [comment]
Maybe I don't know how to update it properly (I replaced all the pervious code with the 1.1.0 code) but the widget shows 1.1.0 and the "Advanced Controls" was new from the initial version.

**Comment by IndyTX** [comment]
Mine got closed out, but I'm having the same issue.  I'm on 1.2.3 (see issue Advanced Controls loop #22)

**Comment by tonesto7** [comment]
Guys i've tested this heavily and the issue was resolved.  Please install the latest version of the script
https://raw.githubusercontent.com/tonesto7/fordpass-scriptable/main/Fordpass%20Widget.js

**Comment by IndyTX** [comment]
Thanks for taking a look at the advanced menu issue.  It isn't that big of a deal, but I wanted you to see what it is doing under 1.3.0

https://user-images.githubusercontent.com/96129104/146657503-b3605083-0a33-48e7-b18f-9eae83c5f4ab.mov

**Comment by tonesto7** [comment]
Thank you very much for the video... I will see if I missed something

**Comment by tonesto7** [comment]
It's weird that mine does not do this.  The only difference in my menu is that I have Zonelighting and Trailer Light Check as well

**Comment by tonesto7** [comment]
I'm finally able to duplicate this :)

Now I just need to understand why it's happening.  
I promise this will be fixed in the next release

**Comment by IndyTX** [comment]
Thanks, and no rush.  I just wanted to make sure you knew about the issue.

**Comment by IndyTX** [comment]
Fixed- Shows SecuriAlert Control and exits with the back button.
