### ISSUE TITLE
Vehicle Images Not Loading, <401 Unauthorized>

### ISSUE THREAD

**Issue by ghartz70** [tonesto7/fordpass-scriptable#122]
The vehicle images won't load in the app for me. 
The log file shows the following info: 

09/12 09:47:17 D OkHttp3: <-- 401 Unauthorized https://www.digitalservices.ford.com/fs/api/v2/vehicles/image/full?vin=<Vin Removed>&year=2022&countryCode=USA&angle=3 (72ms)
09/12 09:47:17 D OkHttp3: <-- 401 Unauthorized https://www.digitalservices.ford.com/fs/api/v2/vehicles/image/full?vin=<Vin Removed>&year=2022&countryCode=USA&angle=5 (68ms)

(Full log attached) 
[fsw_logfile-09-12-09_53_17.txt](https://github.com/tonesto7/fordpass-scriptable/files/9548779/fsw_logfile-09-12-09_53_17.txt)

**Comment by seanmcnally98** [comment]
Having what might be the same issue, no images for me either...how'd you get the log file?  Would love to confirm if it's the same 401 Unauthorized, but I don't seem to see any text files in iCloud drive or any log options in the widget.

**Comment by ghartz70** [comment]
Hey Sean,

I use the app on Android.  Maybe I posted my issue on the incorrect hub?

In any case, for Android at least,  in the settings menu there is an option to turn on logging. 

There is another menu option to save the log file.
The log file saves on the phones' internal storage in the Downloads directory with a name of fsw_logfile-(date).txt
