### ISSUE TITLE
Error On line 992:82 TypeError: undefined is not an object (evaluating 'vehicleData.statusDoors ['leftFront']')/Error: The data couldn't be read because it isn't in the correct format

### ISSUE THREAD

**Issue by itbesandrodoe1** [tonesto7/fordpass-scriptable#13]
I have a 4 Door Big Bend Bronco - not sure if the trim level effects the working of the app? 
My FordPass app does not show windows on it

**Comment by itbesandrodoe1** [comment]
I actually think this is stemming from the pop-up for me to log in not showing up.

**Comment by rcheneyjr** [comment]
I am receiving the same error

**Comment by rcheneyjr** [comment]
New Maverick for me.

**Comment by itbesandrodoe1** [comment]
I am now getting a "Error: The data couldn't be read because it isn't in the correct format."

**Comment by OtherTimDavis** [comment]
I am receiving the same error message, except in my case it is referencing line 989:82

**Comment by tonesto7** [comment]
sorry,  I completely forgot about this.

Please try this version to see if the issue resolves it: 
https://gist.githubusercontent.com/tonesto7/942bda23e3228f16f324bf4e68fec6d2/raw/d9543252644228371054f03a4c16e44e4104f7c2/Fordpass%2520Widget.js

**Comment by tonesto7** [comment]
If you do get the menu to show from the widget please tap on widget settings > debug menu > copy vehicle data and paste it here please

**Comment by OtherTimDavis** [comment]
After trying the version 1.2.1 code, I am able to log in.

Thank you,

Tim
