### ISSUE TITLE
Low battery notification

### ISSUE THREAD

**Issue by IndyTX** [tonesto7/fordpass-scriptable#17]
Low battery notification does not clear, and battery voltage does not set back to the non-alert color.
![Screen Shot 2021-12-15 at 7 57 53 AM](https://user-images.githubusercontent.com/96129104/146214133-28351788-55ce-4ee8-8553-b0b6e7289e85.jpg)
.

**Comment by tonesto7** [comment]
i have another big release coming soon... I will get this fix included.  
Thanks for reporting

**Comment by IndyTX** [comment]
Thanks for all the work you are putting into this!

**Comment by tonesto7** [comment]
For now this alert has been disabled on electric vehicles.  Ford seems to set the STATUS_LOW for your battery state which is why it's red.
