### ISSUE TITLE
Multi Country Support

### ISSUE THREAD

**Issue by juansanchezcastillo** [tonesto7/fordpass-scriptable#18]
First, you did a great work!!!

The Issue:
I use your script in Spain, in order to use it I have to change manually line 2048 (ver 1.2.1) because of the "countryCode".

From:
let req = new Request(`https://www.digitalservices.ford.com/fs/api/v2/vehicles/image/full?vin=${vin}&year=${modelYear}&countryCode=USA&angle=4`);

To:
let req = new Request(`https://www.digitalservices.ford.com/fs/api/v2/vehicles/image/full?vin=${vin}&year=${modelYear}&countryCode=ESP&angle=4`); 

I think there are almost 2/3 URL that use country or countryCode, the main problem in order to be able to run your script is on line 2048

I do not know if Fordpass API info give you the "customer country", but would be a great feature in order to make it multi country without change it manually.

Another issue is with Tire Pressure:
Here in spain we use Bar  and we use Metric system.
Bar = kPa / 100
I have to change line 2075 (ver 1.2.1):
from: //if (!(await usePsiUnit()) && !(await useMetricUnits())) {
to: if (!(await usePsiUnit())) {

In order to see kPA value, because with Metric and kPA selected, the script always shows psi values.

Best regards and keep the great work

**Comment by tonesto7** [comment]
Thanks for the suggestions.  I knew this request was coming sooner or later :)
I will add support for this in the next release v1.3.0.  It might be a day or two from now

**Comment by juansanchezcastillo** [comment]
It's works!!

Great work

Thank you
