### ISSUE TITLE
Image type error.

### ISSUE THREAD

**Issue by sashalondon** [tonesto7/fordpass-scriptable#19]
I get the following error when running the script in scriptable on iOS 15.2. 

![image](https://user-images.githubusercontent.com/8496722/146379842-994eee0c-b135-4c51-8de4-c910838d4e3f.png)

**Comment by tonesto7** [comment]
Does your Fordpass App show an image of your actual vehicle or is it empty?

**Comment by tonesto7** [comment]
Please try this version of the script to confirm if your issue is resolved.
https://gist.githubusercontent.com/tonesto7/942bda23e3228f16f324bf4e68fec6d2/raw/7b6cce61a9ac91f2a14be164cfe76731fb53242e/Fordpass%2520Widget.js

**Comment by sashalondon** [comment]
Hi this works. I can view the widget in stackable. However the widget does not show in the Home Screen as it says "Alerts are not supported in a widget".

**Comment by tonesto7** [comment]
I've seen it before... Just tap on the widget and then it should be good
