### ISSUE TITLE
Error on line 1923:108

### ISSUE THREAD

**Issue by Fordman3519** [tonesto7/fordpass-scriptable#20]
Exception occurred: Error on line 1923:108 TypeError: null is not an object(evaluating ‘windows.driverWindowsPosition’)

I get this error after trying to tap on icon

**Comment by tonesto7** [comment]
that's not even an object in the script.  Are you sure you're running the latest version of the script?
https://raw.githubusercontent.com/tonesto7/fordpass-scriptable/main/Fordpass%20Widget.js

**Comment by Fordman3519** [comment]
![BD365A32-0E5A-40AB-810C-DC7492032D2E](https://user-images.githubusercontent.com/96257499/146625473-70766ca3-f890-4611-9aee-96ece1dde72e.png)

**Comment by Fordman3519** [comment]
This is what I got after adding in the code, I have a 2020 Ford Ranger in FordPass, running iOS version 15.1
