### ISSUE TITLE
Error on line 1814:23

### ISSUE THREAD

**Issue by Lancezw** [tonesto7/fordpass-scriptable#21]
![B6EA6192-2528-40D8-9F0E-BC646E769BBD](https://user-images.githubusercontent.com/96300541/146558063-b73921c0-73dd-464d-8366-ce8c991f9074.jpeg)

![2BF954F1-5F37-456F-9013-4E0F30314BD2](https://user-images.githubusercontent.com/96300541/146558208-205184aa-d4e0-4eca-8c64-4e1cec8fc223.jpeg)

**Comment by tonesto7** [comment]
Hi,

Please try this version of the script and tell me if it solves your issues.
https://gist.githubusercontent.com/...8ead3ec218b97a568a4a79b2/Fordpass%20Widget.js

* Once you've updated the script please perform the following tasks:
* Open the Scriptable app
* Tap on the (...) on Ford pass Widget
* You will now be in the script editor
* Slide up the log window from the bottom
* Press the play button bottom right.
* Perform tasks using the menu and review the output in the logs after saving your login and vin for any errors, and make sure the data looks valid

Review the log output after saving your login and vin for any errors, and make sure the data looks valid

**Comment by Lancezw** [comment]
Appreciate the help. But the link says error not found. 

Thanks,
Lance

**Comment by tonesto7** [comment]
Please update to v1.3.0
https://raw.githubusercontent.com/tonesto7/fordpass-scriptable/main/Fordpass%20Widget.js

**Comment by Lancezw** [comment]
Awesome so that worked but it makes me log in every time to run the script. I went through the directions and followed everything. Any idea?


Thanks,
Lance Zwiener
512-751-1372
