### ISSUE TITLE
Advanced Controls loop

### ISSUE THREAD

**Issue by IndyTX** [tonesto7/fordpass-scriptable#22]
When Advanced Controls is selected, SecuriAlert Control and Back appear.  If SecurityAlert Control is selected, Zone Lighting Control comes up.  If Back is selected from Advanced Controls, it goes to SecuriAlert options. To get out of Advanced Controls, Scriptable has to be stopped/killed. 

![Screen Shot 2021-12-17 at 8 27 51 AM](https://user-images.githubusercontent.com/96129104/146559283-2b0cc81f-5aed-4385-b616-6cbcb8d861da.jpg)

**Comment by tonesto7** [comment]
yeah that was fixed in the v1.2.3 script.  Please update

**Comment by IndyTX** [comment]
I'm running 1.2.3
![Screen Shot 2021-12-17 at 8 59 40 AM](https://user-images.githubusercontent.com/96129104/146563838-caf6b4b0-0be4-4de1-9f6a-d2c631fc044b.jpg)
