### ISSUE TITLE
Error on line 1912:91

### ISSUE THREAD

**Issue by deon918** [tonesto7/fordpass-scriptable#24]
Evaluating battery fill level error
![1085308F-724A-4A21-BA88-E4AA4BEC5E7A](https://user-images.githubusercontent.com/77940918/146601227-88d8ff93-3ba3-46cf-a9c3-26afc76232ca.jpeg)

**Comment by tonesto7** [comment]
Is your vehicle a Mach-E?

**Comment by tonesto7** [comment]
Hi,

Please try this version of the script and tell me if it solves your issues.
https://gist.githubusercontent.com/...8ead3ec218b97a568a4a79b2/Fordpass%20Widget.js

* Once you've updated the script please perform the following tasks:
* Open the Scriptable app
* Tap on the (...) on Ford pass Widget
* You will now be in the script editor
* Slide up the log window from the bottom
* Press the play button bottom right.
* Perform tasks using the menu and review the output in the logs after saving your login and vin for any errors, and make sure the data looks valid

Review the log output after saving your login and vin for any errors, and make sure the data looks valid

**Comment by deon918** [comment]
> 

No i have a 2019 ecosport

**Comment by tonesto7** [comment]
This should be resolved with v1.3.0
https://raw.githubusercontent.com/tonesto7/fordpass-scriptable/main/Fordpass%20Widget.js
