### ISSUE TITLE
“Alerts are not supported in a widget”

### ISSUE THREAD

**Issue by mattwolkoff** [tonesto7/fordpass-scriptable#26]
First, this script is awesome, and thank you for doing this. 

I’m having an issue with the widget. See the attached photo. 
![2A2E8F51-E5FF-491B-8868-5CA9CBB2A423](https://user-images.githubusercontent.com/3586359/146648345-6b3f6acd-fab3-45ef-a650-4f59e70ca800.jpeg)

Is it related to this alert in my fordpass app?
![PNG image 6](https://user-images.githubusercontent.com/3586359/146648427-025487a9-3b7f-456b-9885-2ff0d5a0d3b9.png)

**Comment by tonesto7** [comment]
This occurred in an older version where I had an alert in place for debugging purposes.  Please update to the latest release v1.3.0 and all your issues with the script should be resolved.
https://raw.githubusercontent.com/tonesto7/fordpass-scriptable/main/Fordpass%20Widget.js

If your car is in deep sleep it's likely your 12V battery is low :(
