### ISSUE TITLE
PSI/kPa Tire Pressure Issue

### ISSUE THREAD

**Issue by kayyovx** [tonesto7/fordpass-scriptable#28]
Just updated to the newest version of the script. The app is also up to date. Trying to change the tire pressure from kPa to PSI. Tried going to the widget settings prompt and clicking Pressure Units to change as it did on the previous version, this doesn’t change that issue.. still repeatedly shows only kPa, PSI does not show.

**Comment by tonesto7** [comment]
Thanks for reporting i will look into this and get a patch out ASAP

**Comment by tonesto7** [comment]
The widget reads the units of measure for pressure and distance from your ford account starting with v1.2.0. 
I'm trying to find out why some people are not seeing the correct data.

**Comment by kayyovx** [comment]
> The widget reads the units of measure for pressure and distance from your ford account starting with v1.2.0.
> I'm trying to find out why some people are not seeing the correct data.

It’s kind of weird because it did work in the previous version, compared to now. Not sure why!

**Comment by tonesto7** [comment]
I've tracked down the issue and will have a fix out this evening.

**Comment by kayyovx** [comment]
Awesome, thanks! 👍🏼
