### ISSUE TITLE
Required Settings Missing

### ISSUE THREAD

**Issue by pookaknight** [tonesto7/fordpass-scriptable#29]
I updated to 1.3.0, and now every time I run the script, it comes up with a message saying Required Settings Missing. It has the screen to put in my Fordpass username and password and the vehicle VIN. All three are already filled out, but I have to click save every time. The widget doesn’t display. Instead, it says “Alerts are not supported in a widget.” I imagine it’s happening because it’s doesn’t think it has the Fordpass credentials.

**Comment by tonesto7** [comment]
Sorry about that... There was deviceLanguage variable that is pulled from the ford API.  Apparently, it's not available on every user's account.  I'm removing the requirement for the variable in the next release.

**Comment by tonesto7** [comment]
please update to v1.3.2 and this issue is resolved.
