### ISSUE TITLE
Oil Life shows "No Data"

### ISSUE THREAD

**Issue by tkljr** [tonesto7/fordpass-scriptable#3]
"Fordpass" app shows proper value of "25%" but the widget shows "No Data". All other widget data appears correct.

**Comment by tkljr** [comment]
Update: I just started the truck and shut it off and now show the proper oil life data.

**Comment by tonesto7** [comment]
It's the way that the vehicle reports data to ford. It does the same with fuel as well.  After the vehicle has been off for a bit sometimes it loses it's fuel and oil states.
