### ISSUE TITLE
Keep getting this error have redone it 5X not sure what the deal is

### ISSUE THREAD

**Issue by Rkenjalo** [tonesto7/fordpass-scriptable#33]
![5D51B223-E6E8-4E36-A755-5DA829FD7F6F](https://user-images.githubusercontent.com/96364156/146692349-bebbc236-633b-4b9b-974f-18de0d0e6f6c.png)

**Comment by tonesto7** [comment]
I've added better handling of missing data.  Please update to v1.3.2 of the script after 10:30am EST today

**Comment by Rkenjalo** [comment]
Thank you appreciate it

**Comment by Rkenjalo** [comment]
Same thing. I don’t know what the heck. Is it something on my end?

**Comment by Rkenjalo** [comment]
I’ve tried erasing everything and redoing it all I still get the same
thing. Any ideas? I love the widget and would love for it to work
