### ISSUE TITLE
Exception Occurred Error on line 2208:108 TypeError: null

### ISSUE THREAD

**Issue by jasperpants** [tonesto7/fordpass-scriptable#34]
Exception Occurred Error on line 2208:108 TypeError: null is not an object (evaluating 'windows.driverWindowPosition')

This is with v1.3.2 and a Ford Maverick.

**Comment by tonesto7** [comment]
This is interesting... The maverick doesn't seem to keep track of the window position. 
I have added checks to prevent this error

Please try this version: https://gist.githubusercontent.com/tonesto7/942bda23e3228f16f324bf4e68fec6d2/raw/f526d6d538757f10721cf175fdf3ec5c1dfc6cff/Fordpass%2520Widget.js

**Comment by jasperpants** [comment]
Thanks, tried the script but it errored for the same object on different line:

Error on line 2214:27: TypeError: null is not an object (evaluating 'windows.driverWindowPosition')

**Comment by tonesto7** [comment]
Wow it must not even have the window object... 
Try this: https://gist.githubusercontent.com/tonesto7/942bda23e3228f16f324bf4e68fec6d2/raw/745a31d896b62e0ec93c18dfa3d8636290660c91/Fordpass%2520Widget.js

**Comment by jasperpants** [comment]
Yes!  That works!!!!
