### ISSUE TITLE
No longer updating in minutes 

### ISSUE THREAD

**Issue by kayyovx** [tonesto7/fordpass-scriptable#36]
The widget isn’t updating every few mins, takes hours. App and script are both up to date. 

![6350BE18-B31C-4DB4-8C09-679BD08513C0](https://user-images.githubusercontent.com/96359672/146865917-8ad469e5-5e26-4eed-b840-5d69981dd96e.jpeg)

**Comment by tonesto7** [comment]
It's still updating... The timestamp reflects when the car last sent data into ford.

**Comment by kayyovx** [comment]
Awesome, thanks for the clarification!
