### ISSUE TITLE
VIN not scrubbed from "relevantVin" inside "messages"

### ISSUE THREAD

**Issue by jasperpants** [tonesto7/fordpass-scriptable#38]
When viewing Vehicle Data Output the "vin" is scrubbed to remove personal data but it also appears in the messages returned from Ford's servers thereby exposing the users VIN number.  The field is "relevantVin".  If that can be scrubbed the same way as "vin" that would be great!

Example:

  {
                "id": "2",
                "messageId": "xxxxxxxx",
                "messageSubject": "Put Your FordPass™ Reward Points to Use.",
                "messageBody": "Your Points can be used toward complimentary maintenance* — including your first oil change. You can even save them and use them towards the purchase of your next Ford vehicle!*Must be enrolled in FordPass Rewards to receive Points. See ",
                "messageType": "EXTERNALNOTIFICATIONREQUEST",
                "createdDate": "12/16/2021 09:52:57 PM",
                "priority": 1,
                "messageTypeId": 20001,
                "highlighted": true,
                "relevantVin": "3FTTW8E92NRXXXXXX",
                "contentType": "Html",
                "metadata": "{\"DeliveryId\":\"1XXXXXXX|USA\",\"PegaInteractionId\":\"XXXXXXX\"}",
                "isRead": true
            },

**Comment by tonesto7** [comment]
thanks for catching that

**Comment by tonesto7** [comment]
this has been resolved and will rollout with v1.4.0
