### ISSUE TITLE
Fuel percentage and oil life intermittently display incorrect data

### ISSUE THREAD

**Issue by ChadB479** [tonesto7/fordpass-scriptable#45]
![DC9FBBDF-B7B1-4679-97FC-AC0D24BEC305](https://user-images.githubusercontent.com/96384466/147160799-dd5d3ed8-452f-4ea6-90d0-36fbf43d96cb.jpeg)

**Comment by ChadB479** [comment]
Notice it shows correct mi to E data. Data drops and returns intermittently without having driven the vehicle

**Comment by tonesto7** [comment]
This is because ford loses the data sometimes.  I can only work with the data I receive.  I had an issue pinned for this.
