### ISSUE TITLE
Not updating per defined interval?

### ISSUE THREAD

**Issue by Igmiller** [tonesto7/fordpass-scriptable#46]
With the latest 1.3.3 version, my widget doesn’t refresh at the default 5 min window.  It’s showing many hours instead between refreshes.   I’ve wiped it and redid the whole widget and still not refreshing.  Anyway to down grade to 1.3.2 or 1.3.1?

**Comment by tonesto7** [comment]
It's updating correctly.  The timestamp now reflects the last time your vehicle checked in with Ford servers
