### ISSUE TITLE
No Vehicle Image for the 2022 Maverick

### ISSUE THREAD

**Issue by realLianghao** [tonesto7/fordpass-scriptable#50]
Not sure if it's a problem on the Ford side or not, but my widget just shows the placeholder image.

![IMG_0241](https://user-images.githubusercontent.com/44045861/147803076-d60979f5-3d8e-4cc4-b53d-872b959e4559.png)
.

**Comment by wjohnson1186** [comment]
I think the Maverick image is [showing up now](https://imgur.com/a/wp6CTPv)?

**Comment by tonesto7** [comment]
There were changes to the image api.  
I have them resolved in the upcoming V2.0. 

I still have quite a few features to finish before I release. 
It might be 2 weeks for full release and another week before beta.

**Comment by realLianghao** [comment]
> There were changes to the image api. I have them resolved in the upcoming V2.0.
> 
> I still have quite a few features to finish before I release. It might be 2 weeks for full release and another week before beta.

That's good to know, thank you for your work!

**Comment by realLianghao** [comment]
It appears to be working now.
