### ISSUE TITLE
Tire Pressure only shows front tires

### ISSUE THREAD

**Issue by gehogan3** [tonesto7/fordpass-scriptable#6]
Probably another "small screen" issue, but the tire pressure show up as:

33.2 | 32.1...

With no second line for the rear tires.

**Comment by gehogan3** [comment]
Changing the detailFontSizeSmall and detailFontSizeMedium to both 9 made it display all numbers.
These settings for fonts seem to make everything visible on my iPhone X:

const sizes = {
    titleFontSize: 9,
    detailFontSizeSmall: 8,
    detailFontSizeMedium: 9,
    detailFontSizeBig: 19,
    barWidth: 80,
    barHeight: 10,
};

**Comment by tonesto7** [comment]
This resolved with v1.1.1 of the script.  please update
