### ISSUE TITLE
Multiple Ford Pass Vehicles

### ISSUE THREAD

**Issue by Kard10** [tonesto7/fordpass-scriptable#7]
It looks like the Apple Keychain settings are being overlapped when trying to setup a second Ford Pass Vehicle. Changing those keychains to be named something different was easy enough, but I can't seem to get the Vehicle Image to stick per widget/car. One of them will default to the other after a few minutes, even after clearing the keychain settings and entering again.

**Comment by tonesto7** [comment]
I knew this was going to occur on the first day...  I need to use the vin number in the file names to allow multiple.  
I will add support for multiple in the next release.

**Comment by tonesto7** [comment]
I never had a chance to get to this for v1.2.0.   I need to create a migration function to move existing data over to the new format

**Comment by Kard10** [comment]
Might be able to just make a note on the next update to have users clear the settings and enter the login/VIN again. Obviously not ideal but probably not too painful either this early.

**Comment by tonesto7** [comment]
I've spent some time on this but I'm struggling to come up with a good way to identify the running script so I can tag the saved data for that script.  There is no accessible id tied to the running script instance.  
Aside from using the widget name or adding a hard coded variable to the script.  There are not many options.

**Comment by tonesto7** [comment]
I was trying to do this in a way that didn't require updating the code in the script.  That way you can easily update the script without having to edit each one.  
I've added a SCRIPT_ID variable to the top of the script.  Its default is 0 so any additional instances need to be incremented for each one. 

This will allow storing of separate data and credentials for each

**Comment by Kard10** [comment]
The instances worked for displaying the correct information for each vehicle, but it looks like the vehicle picture is still being shared/overwritten for both vehicles.

**Comment by tonesto7** [comment]
This is fixed in v1.3.2  

Please check for the update after 10:30am EST

**Comment by Kard10** [comment]
Looks like I’m getting an error now for my widget that I set with instance “1”.
![ADF8BB60-7237-41C2-A139-A6041E329810](https://user-images.githubusercontent.com/96094927/146808832-ca153eb4-d430-486f-b8f9-7e720bef8b39.jpeg)

**Comment by Kard10** [comment]
Same error with version 1.3.3. Updated screenshot with current location of error.
![4E17E735-2255-4E5A-9394-D332F5BCB313](https://user-images.githubusercontent.com/96094927/146878779-9d7806ef-aa3b-4916-848d-7bbc2b20340f.jpeg)

**Comment by Kard10** [comment]
Latest version (v1.4) appears to have some sort of issue. The widget shows up as blank and the the script no longer brings up any options. There are no error messages this time, but nothing happens after running the script. My vehicle with script ID 0 is working as expected. I tried using a script ID value that I had not used before for the second vehicle and it gave the same result.

![PNG image](https://user-images.githubusercontent.com/96094927/147497427-b199b280-e02e-4729-89df-d394cdf3e478.png)
.
