### ISSUE TITLE
Mach E, Door Objects Undefined

### ISSUE THREAD

**Issue by cskerbo** [tonesto7/fordpass-scriptable#8]
On the Beta version 1.1.0, for the Mach-E, I am receiving the following error:

Error on line 893:82: TypeError: undefined if not an object (evaluating 'vehicleData.statusDoors['leftFront']')

Haven't commented out to go further, but I this is the first door in the code - I am assuming that all of the doors are sowing undefined for the Mach-E.

**Comment by tonesto7** [comment]
I can't help with this little data... I need to see my info.
Make sure you are running the latest version 1.1.1

**Comment by tonesto7** [comment]
Make sure to update to the latest script.  I think I have this issue sorted out now.
