### ISSUE TITLE
TPMS bull error

### ISSUE THREAD

**Issue by kpkimmel1983** [tonesto7/fordpass-scriptable#84]
When logging in I get this error - I have a Ford raptor and TPMS does not show in FordPass app.

null is not an object evaluating tpms.frontlefttirepreaaure.value

**Comment by kpkimmel1983** [comment]
![104F4BD7-45B3-4036-8D01-66B4687E30B2](https://user-images.githubusercontent.com/41630988/160847951-86532fe7-07af-441f-8dc6-81e68d4d9072.jpeg)

**Comment by tonesto7** [comment]
thanks for reporting i've added in some checks to help eliminate the error.
They will be included in the next release.
